# Generated by Django 4.2.1 on 2023-05-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='scoreboard_status',
            field=models.CharField(choices=[('visible', 'Visible'), ('frozen', 'Frozen'), ('released', 'Released')], default='visible', max_length=100),
        ),
    ]
