# Generated by Django 4.2.1 on 2023-05-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_contest_scoreboard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboarduser',
            name='telegram_chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
