# Generated by Django 4.2.1 on 2023-05-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_scoreboarduser_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='scoreboard_status',
            field=models.CharField(choices=[('invisible', 'Invisible'), ('visible', 'Visible'), ('frozen', 'Frozen'), ('released', 'Released')], default='invisible', max_length=100),
        ),
    ]
