# Generated by Django 4.2.1 on 2023-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_contest_scoreboard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='scoreboard_status',
            field=models.CharField(choices=[('invisible', 'Invisible'), ('visible', 'Visible'), ('frozen', 'Frozen'), ('waiting_to_be_released', 'Waiting To Be Released'), ('released', 'Released'), ('archived', 'Archived')], default='invisible', max_length=100),
        ),
    ]
