# Generated by Django 4.2.1 on 2023-08-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_contest_scoreboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='max_teams_per_school_to_advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_teams_to_advance',
            field=models.IntegerField(null=True),
        ),
    ]
