# Generated by Django 4.2.1 on 2024-03-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_contest_max_teams_per_school_to_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboardsubscription',
            name='top',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoreboardsubscription',
            name='subscription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
