# Generated by Django 4.2.1 on 2026-04-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_scoreboardsubscription_top_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboarduser',
            name='telegram_chat_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
